### PR TITLE
Feature: Export models with skeleton

### PR DESCRIPTION
**Pull request by ryanjsims**
This change adds support for exporting skeletons from unit files.

Currently the bones' local transforms are not correctly converted from Stingray global coordinates to gltf local coordinates, but resetting the pose in Blender will get the skeleton into the correct orientation. This isn't a big deal right now, but once we start exporting animations as well it will be more important to have the bones oriented correctly.

To enable skeleton export, there is a new unit config option `bones` that can either be `disabled` (default) or `enabled`.

Here's an example of a bile titan with all its bones visible (after resetting the pose)

image

and an example animation using only a couple of IK constraints on the exported bones

https://github.com/xypwn/filediver/assets/31775294/c1f72fdc-65fe-4de9-bf64-5d648508b57a

### CODE REVIEW

**Comment by xypwn** [comment]
Wow! Your results look great so far!

Can you tell me more about how you managed to create the animation you shared? When I load the model into blender, the bones are just huge spheres. I'd like to merge this PR once I can understand how it's directly useful to non-technical people using the app. But maybe I'm just missing something since I'm not very educated in terms of 3D art / blender.

Also, you mentioned creating IK constraints yourself. If you pass `-c "enable:all"`, you can see all the file types (including raw). One of them is `ìk_skeleton` (e.g. `content/fac_bugs/cha_strider/cha_strider.ik_skeleton` for the bile titan). Did you look into parsing it yet?

In any case, nice work so far! I love seeing this project move forward although I don't have a lot of time to dedicate to it right now.

**Comment by xypwn** [comment]
Don't worry about the conflicts I created with my last commit, I'll resolve them before merging.

**Comment by ryanjsims** [comment]
> One of them is ìk_skeleton (e.g. content/fac_bugs/cha_strider/cha_strider.ik_skeleton for the bile titan). Did you look into parsing it yet?

Yes, if you look at the `research/hex-patterns` branch on my fork, in the patterns folder I have an ik_skeleton hex pattern for use with ImHex. I have parsed the very broad strokes of that file type, but I haven't gotten into the actual details of it yet

As for the huge spheres, that sounds like something with how blender is configured to display bones? Could you add a screenshot?

**Comment by xypwn** [comment]
> Yes, if you look at the research/hex-patterns branch on my fork, in the patterns folder I have an ik_skeleton hex pattern for use with ImHex. I have parsed the very broad strokes of that file type, but I haven't gotten into the actual details of it yet

Great to hear! Let me know if you find anything interesting.

> As for the huge spheres, that sounds like something with how blender is configured to display bones? Could you add a screenshot?

Sure, here are the spheres...
grafik
... and the bile titan at the same zoom level
grafik

Blender version is 4.0. I didn't change any blender settings AFAIK. Are you using a different version?

**Comment by ryanjsims** [comment]
Found this video about it: https://www.youtube.com/watch?v=U5XboSEw7-o

Looks like it has to do with viewport display -> shapes being selected? I've never seen that happen with gltf skeletons before in blender. I also saw some people saying there is a setting in the import menu about "Bone Shape" that can be set to default to prevent it from happening, but I don't see that option when importing gltf files

**Comment by xypwn** [comment]
Thanks! Setting Bone Dir to Temperance did the trick!
grafik

It looks like your screenshot now
grafik

**Comment by xypwn** [comment]
Well, I guess that's good enough to merge into main for now. I'm very excited to see how this will continue to improve with IK and proper pose positioning.

Thanks again for your work on this!

**Comment by ryanjsims** [comment]
I'm not sure if we'll be able to implement IK on export to gltf since I don't think the format supports it - the IK skeleton should have some interesting data, which will probably be useful somehow. We may need to add a second format if we want to have IK exported. Maybe direct to .blend?

**Comment by xypwn** [comment]
Hmm, I guess that's true. I just assumed without knowing that there'd be a standard for IK, allowing for exports/imports, but apparently there's nothing like that. While it might have some interesting data, I think focusing on animations and getting the pose to work correctly is probably more important right now.

**Pull request merged**
